### PR TITLE
Dev1.7.10

### PR DESCRIPTION
**Pull request by sfxworks**
Here ya lol the server is good without the killlups.sh script for some apparent reason but it works mk

### CODE REVIEW

**Comment by sfxworks** [comment]
I dont like this but i guess it is cool

**Comment by LupusWhiteFur** [comment]
Best Change

**Comment by madwolfpack** [comment]
I wanna comment to :)

**Comment by sfxworks** [comment]
MAD IS A MAD STALKER YO

**Comment by madwolfpack** [comment]
Ya know it
>_>

**Comment by madwolfpack** [comment]
KEK
SPAM

**Comment by madwolfpack** [comment]
SPAM

**Comment by madwolfpack** [comment]
SPAM

**Comment by madwolfpack** [comment]
SPAM

**Comment by madwolfpack** [comment]
SPAM

**Comment by madwolfpack** [comment]
SPAM

**Pull request merged**
